files:
  - source: /app/src/main/res/values/*.xml
    ignore:
      - /**/attrs.xml
      - /**/colors.xml
      - /**/dimens.xml
      - /**/ic_*.xml
      - /**/themes*.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
